# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghost" do
  name "ghost"
  desc "A ghost in your terminal"
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghost"

  on_macos do
    on_intel do
      url "https://github.com/ukashazia/ghost/releases/download/v#{version}/ghost_Darwin_x86_64.tar.gz"
      sha256 "1e5eb185d699cbad2b6ded2620a9e2f670c07040652708ec763885b59e26d9b0"
    end
    on_arm do
      url "https://github.com/ukashazia/ghost/releases/download/v#{version}/ghost_Darwin_arm64.tar.gz"
      sha256 "35cb4dad105ee124aaee561f9c4728bc31ac8cd21dd8a3af66cb94fb23125c4d"
    end
  end

  # No zap stanza required
end
